version: '3'
services:
    node:
        container_name: e-xode.vui
        build:
            context: 'docker/dev'
        volumes:
            - '.:/app'
        ports:
            - 3001:3001
        env_file:
            - ./.env
        networks:
            - e-xode
networks:
  e-xode:
    driver: bridge
    external: true
